### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by henare** [planningalerts-scrapers/spear#3]
Lots of applications on this scraper are missing descriptions, this means they don't get added to PlanningAlerts.

It looks like this is because the source is missing an 'Intended use' field. Maybe when that's missing we could just use 'Application Type' as it seems to be a reasonable alternative in the situations I've looked at.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e69x)

**Comment by jamezpolley** [comment]
This is still an issue

**Comment by jamezpolley** [comment]
This is still an issue.

**Comment by mlandauer** [comment]
Fixed by https://github.com/planningalerts-scrapers/spear/pull/4
